[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/src',
    'solady/=lib/solady/src/',
    'solady-test/=lib/solady/test/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'shipyard-core/=src/',
    'seaport-types/=lib/seaport-types/src/',
    'solarray/=lib/solarray/src/',
]
# bytecode_hash = 'none'
ignored_error_codes = ['license', 'code-size', 'init-code-size']
optimizer_runs = 99_999_999

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
